In [13]:
import torch
from sklearn.datasets import make_classification
from torch.utils.data import Dataset, DataLoader

In [14]:
X, y = make_classification(
    n_samples=500,
    n_features=10, 
    n_informative=10,
    n_classes=2,
    n_redundant=0,
    random_state=42
)

In [15]:
X

array([[-2.45099228,  1.02271267,  1.92298861, ...,  2.36881705,
        -2.73348836,  1.34267914],
       [ 0.54032231,  1.03425995, -1.63701469, ..., -1.95118503,
        -0.54577865, -2.37951324],
       [-1.25511111,  0.53493002,  2.58305601, ...,  3.15283843,
        -0.97497099, -2.23412032],
       ...,
       [-0.22669206,  1.83908446,  0.6674825 , ..., -2.59128402,
        -0.36035374,  3.13561248],
       [ 1.09160289, -0.6694464 , -0.20911683, ...,  0.58416907,
         2.46376495, -1.39798043],
       [ 0.53975858,  5.95818911, -0.87658576, ..., -0.53243557,
         2.47505545,  4.37529242]])

In [16]:
y

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,

In [17]:
X.shape

(500, 10)

In [18]:
y.shape

(500,)

In [19]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [20]:
class CustomDataset(Dataset):
    def __init__(self, n_features, labels):
        self.features = n_features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [21]:
dataset = CustomDataset(X, y)

In [25]:
len(dataset)

500

In [23]:
dataset[0]

(tensor([-2.4510,  1.0227,  1.9230, -1.2610, -1.0535, -0.0650,  0.8211,  2.3688,
         -2.7335,  1.3427]),
 tensor(0.))

In [26]:
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

In [27]:
for batch_features , batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("---"*50)

tensor([[ 1.4942,  0.8585,  2.1731, -2.2695,  1.9689,  3.0613,  0.8398, -1.4033,
          0.7896,  1.2826],
        [-0.0103, -1.6206,  0.3010,  3.2722,  1.7506, -1.4347,  0.9592,  0.7288,
         -2.0113,  1.5656],
        [ 5.1656,  1.7924,  5.5361, -1.3329,  2.7369,  0.8176,  2.0860,  1.1336,
          1.2782, -1.7447],
        [ 0.5025,  0.1299, -1.9268,  2.2359,  1.2026, -0.0465, -1.4855,  1.5658,
          2.4032, -1.7940],
        [ 1.0669, -0.8385,  0.9134, -0.3731, -0.6677, -2.0520, -2.1913,  0.4178,
         -1.1887, -2.2229],
        [-0.3423, -0.2534,  2.8447, -0.5379, -1.9245,  4.3532, -1.3296, -1.2456,
         -0.3689,  0.2978],
        [-3.9546, -4.1008, -0.1786,  1.7825, -0.4482,  3.3365, -2.2140,  0.4096,
          1.2647,  1.2188],
        [-0.5094, -4.1318, -0.4165, -0.6611,  1.4334,  0.3466,  1.0611, -1.3167,
          0.2654, -1.8449],
        [ 0.0486, -0.5649,  0.7705, -2.3922, -0.3424,  1.2537, -4.4888,  0.8385,
         -0.7327,  5.2819],
        [-2.2904, -