In [39]:
from sklearn.datasets import make_classification
import torch

In [40]:
# creating a syntetic classification dataset using sklearn
X, y = make_classification(
    n_samples = 10,  # Total number of data points (rows).
    n_features= 2, # Each sample has 2 input features -- (x1, x2)
    n_informative = 2, # Out of all features, 2 features actually matter for classification
    n_redundant= 0, # No duplicate or correlated features
    n_classes = 2, # Binary classification problem.
    random_state= 42 # Fixes the randomness so results are reproducible.
)

In [41]:
X


array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [42]:
X.shape

(10, 2)

# Converting the data to PyTorch Tensor

In [43]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [44]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [45]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [46]:
from torch.utils.data import Dataset , DataLoader

In [47]:
class CustomDataset(Dataset):

  # constructor
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

 # length
  def __len__(self):
    return self.features.shape[0]

# getitem
  def __getitem__(self, index):
    return self.features[index], self.labels[index]


In [48]:
dataset = CustomDataset(X,y)

In [49]:
len(dataset)

10

In [50]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1.))

# DataLoader

In [51]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [52]:
for batch_features , batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)

  print("--"*30)

tensor([[-2.8954,  1.9769],
        [-0.5872, -1.9717]])
tensor([0., 0.])
------------------------------------------------------------
tensor([[1.7774, 1.5116],
        [1.8997, 0.8344]])
tensor([1., 1.])
------------------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [ 1.7273, -1.1858]])
tensor([1., 1.])
------------------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606]])
tensor([0., 0.])
------------------------------------------------------------
tensor([[-1.1402, -0.8388],
        [-0.9382, -0.5430]])
tensor([0., 1.])
------------------------------------------------------------
