In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [5]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU.")

GPU is available
Using GPU : Tesla T4


## Creating Tensor


In [11]:
# using empty
torch.empty(2) # means 2 values
torch.empty(1) # single number
a = torch.empty(3,3) # 3 rows, 3 columns

In [12]:
# type
type(a)

torch.Tensor

In [13]:
# using zeros
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# using rand
torch.rand(3,3)

tensor([[0.1765, 0.4186, 0.7075],
        [0.7613, 0.4129, 0.9074],
        [0.4948, 0.5684, 0.2531]])

In [17]:
# using seed - means random values will be fix for next time run
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
# using tensor - you will create custom tensor based on your own requirements
torch.tensor([1]) # single number 0-tensor

tensor([1])

In [21]:
torch.tensor([1,3])

tensor([1, 3])

In [23]:
torch.tensor([[1,2], [2,3], [3,4], [4,5], [6,7]])

tensor([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [6, 7]])

In [30]:
# Other ways
# arrange
print("using arange --> ", torch.arange(1,10))
print("using arange --> ", torch.arange(0,10))
print("using arange --> ", torch.arange(0,10,2))
print("using arange --> ", torch.arange(1, 20, 4))

using arange -->  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange -->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange -->  tensor([0, 2, 4, 6, 8])
using arange -->  tensor([ 1,  5,  9, 13, 17])


In [32]:
# Linearly Space Valued
print("Linearly Space Value --> ", torch.linspace(1,10, 5)) #(staring point, ending_Point, No_of_linear_spaced)

Linearly Space Value -->  tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


In [38]:
# Eye - Identity matrix
print("Using Eye for identy matrix --> ", torch.eye(5))

Using Eye for identy matrix -->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [39]:
# using full
print("Using full --> ", torch.full((3,3), 5))

Using full -->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [47]:
x = torch.tensor([[2,4,5], [3,4,5], [2,8,9], [4,4,4]])
print(x)
print("shape of the  tensor => ", x.shape)

tensor([[2, 4, 5],
        [3, 4, 5],
        [2, 8, 9],
        [4, 4, 4]])
shape of the  tensor =>  torch.Size([4, 3])


In [48]:
# copy the shape of the old tensor
torch.empty_like(x)

tensor([[8245936378171564576, 4189038638018098015, 7308535291868164896],
        [4189017755886051700, 7089066514118245152, 7304684000134132831],
        [7954884616478093432, 8888733723603526004, 7020653758400525346],
        [8029111232481092973, 3196848897186887012, 7307199746910528032]])

In [49]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [56]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [57]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor Data Types

In [53]:
# find the datatype
x.dtype

torch.int64

In [54]:
# assign the data type -- flot se integer mein change kar diya
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [55]:
y = torch.tensor([1,4,8,9], dtype=torch.float64)
print("Changing interger into float values --> ", y )

Changing interger into float values -->  tensor([1., 4., 8., 9.], dtype=torch.float64)


# Mathematical Operations


## 1. Scalar

In [59]:
x = torch.tensor([2,2])
print(x)

tensor([2, 2])


In [63]:
# Addition
print("Addition = ", x+2)

# Substraction
print("Substraction = ", x-2)

# Multiplication
print("Multiplication = ", x*2)

# Division
print("Division = " , x/2)

# integer division
print("Interge division = ", (x * 100) / 10)

# Moduls
print("Modulu = ", x%2)
print("Modulu = ", (x*100) % 2)

# Power
print("Power", x**2)

Addition =  tensor([4, 4])
Substraction =  tensor([0, 0])
Multiplication =  tensor([4, 4])
Division =  tensor([1., 1.])
Interge division =  tensor([20., 20.])
Modulu =  tensor([0, 0])
Modulu =  tensor([0, 0])
Power tensor([4, 4])


# Element wise operations

In [67]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)

tensor([[0.0169, 0.2209],
        [0.9535, 0.7064]])
tensor([[0.1629, 0.8902],
        [0.5163, 0.0359]])


In [71]:
print("Addition --> ", a+b)
print("Substraction --> " , a-b)
print("Multiplication --> ", a * b)
print("Division --> ", a / b)
print("Modulu --> ", a % b)
print("Power -> ", a ** b)

Addition -->  tensor([[0.1798, 1.1111],
        [1.4698, 0.7423]])
Substraction -->  tensor([[-0.1460, -0.6693],
        [ 0.4373,  0.6705]])
Multiplication -->  tensor([[0.0028, 0.1966],
        [0.4923, 0.0253]])
Division -->  tensor([[ 0.1038,  0.2481],
        [ 1.8470, 19.6854]])
Modulu -->  tensor([[0.0169, 0.2209],
        [0.4373, 0.0246]])
Power ->  tensor([[0.5145, 0.2607],
        [0.9757, 0.9876]])


In [79]:
c = torch.tensor([1,-2, 3, 5, 0.99])
print("Absolute value -> ", torch.abs(c))
print("Negative -> ", torch.neg(c))
print("Round ->", torch.round(c))
print("Ciel -> ", torch.ceil(c))
print("Floor -> ", torch.floor(c))
print("Clamp -> ", torch.clamp(c, min=1, max=5))

Absolute value ->  tensor([1.0000, 2.0000, 3.0000, 5.0000, 0.9900])
Negative ->  tensor([-1.0000,  2.0000, -3.0000, -5.0000, -0.9900])
Round -> tensor([ 1., -2.,  3.,  5.,  1.])
Ciel ->  tensor([ 1., -2.,  3.,  5.,  1.])
Floor ->  tensor([ 1., -2.,  3.,  5.,  0.])
Clamp ->  tensor([1., 1., 3., 5., 1.])


# Reduction Operations

In [102]:
e = torch.randint(size=(2,3), low=1, high=7, dtype=torch.float32)
print(e)

tensor([[1., 1., 1.],
        [5., 4., 1.]])


In [103]:
print("Sum", torch.sum(e))
print("Columns wise sum -> ", torch.sum(e, dim=0))
print("Rows wise sum -> ", torch.sum(e, dim=1))
print("Mean -> ", torch.mean(e))
print("Columns wise mean -> ", torch.mean(e, dim=0))
print("Row wise Mean -> ", torch.mean(e, dim=1))
print('Median-> ', torch.median(e))
print(' Columns wise Median-> ', torch.median(e, dim=0))
print(' Row wise Median-> ', torch.median(e, dim=1))

# find max , min
print("Max = ", torch.max(e))
print("Columns wise max = ", torch.max(e, dim=0))
print("Row wise max = ", torch.max(e, dim=1))
print("Min = ", torch.min(e))
print("Columns wise min = ", torch.min(e, dim=0))
print("Row wise min = ", torch.min(e, dim=1))



Sum tensor(13.)
Columns wise sum ->  tensor([6., 5., 2.])
Rows wise sum ->  tensor([ 3., 10.])
Mean ->  tensor(2.1667)
Columns wise mean ->  tensor([3.0000, 2.5000, 1.0000])
Row wise Mean ->  tensor([1.0000, 3.3333])
Median->  tensor(1.)
 Columns wise Median->  torch.return_types.median(
values=tensor([1., 1., 1.]),
indices=tensor([0, 0, 0]))
 Row wise Median->  torch.return_types.median(
values=tensor([1., 4.]),
indices=tensor([1, 1]))
Max =  tensor(5.)
Columns wise max =  torch.return_types.max(
values=tensor([5., 4., 1.]),
indices=tensor([1, 1, 0]))
Row wise max =  torch.return_types.max(
values=tensor([1., 5.]),
indices=tensor([0, 0]))
Min =  tensor(1.)
Columns wise min =  torch.return_types.min(
values=tensor([1., 1., 1.]),
indices=tensor([0, 0, 0]))
Row wise min =  torch.return_types.min(
values=tensor([1., 1.]),
indices=tensor([0, 2]))


In [97]:
# product
torch.prod(e)

tensor(144.)

In [98]:
# standard deviation
torch.std(e)

tensor(1.9408)

In [99]:
# variance
torch.var(e)

tensor(3.7667)

In [104]:
# argmax
torch.argmax(e)

tensor(3)

In [105]:
# argmin
torch.argmin(e)

tensor(0)

# 4. Matrix operations

In [106]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[3, 8, 5],
        [6, 2, 9]])
tensor([[5, 0],
        [4, 2],
        [7, 1]])


In [107]:
# matrix multiplcation
torch.matmul(f,g)

tensor([[ 82,  21],
        [101,  13]])

In [110]:
# Dot product
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
print(vector1)
print(vector2)

# dot product
torch.dot(vector1, vector2)

tensor([1, 2])
tensor([3, 4])


tensor(11)

In [114]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [8, 2],
        [5, 9]])

In [116]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(h)

tensor([[2., 5., 6.],
        [1., 4., 5.],
        [6., 9., 2.]])


In [117]:
# determinant
torch.det(h)

tensor(-24.0000)

In [118]:
# inverse
torch.inverse(h)

tensor([[ 1.5417, -1.8333, -0.0417],
        [-1.1667,  1.3333,  0.1667],
        [ 0.6250, -0.5000, -0.1250]])

#5. Comparison operations

In [119]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 1, 0],
        [2, 1, 2]])
tensor([[7, 9, 2],
        [4, 6, 6]])


In [121]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >=j
# less than equal to
i<=j

tensor([[True, True, True],
        [True, True, True]])

# 6. Special functions

In [122]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 4., 9.],
        [0., 7., 9.]])

In [123]:
# log
torch.log(k)

tensor([[2.0794, 1.3863, 2.1972],
        [  -inf, 1.9459, 2.1972]])

In [124]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 5.4598e+01, 8.1031e+03],
        [1.0000e+00, 1.0966e+03, 8.1031e+03]])

In [125]:
# sqrt
torch.sqrt(k)


tensor([[2.8284, 2.0000, 3.0000],
        [0.0000, 2.6458, 3.0000]])

In [126]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9820, 0.9999],
        [0.5000, 0.9991, 0.9999]])

In [127]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.9966e-01, 4.7426e-02, 5.0000e-01],
        [3.3535e-04, 9.5257e-01, 5.0000e-01]])

In [128]:
# relu
torch.relu(k)

tensor([[8., 4., 9.],
        [0., 7., 9.]])

# Inplace Operations

In [129]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.5057, 0.5688, 0.0634],
        [0.8993, 0.2732, 0.3397]])
tensor([[0.1879, 0.5534, 0.2682],
        [0.9556, 0.9761, 0.5934]])


In [130]:
m.add_(n) # store in the same place m []

tensor([[0.6936, 1.1222, 0.3315],
        [1.8549, 1.2494, 0.9331]])

In [131]:
m

tensor([[0.6936, 1.1222, 0.3315],
        [1.8549, 1.2494, 0.9331]])

In [132]:
n

tensor([[0.1879, 0.5534, 0.2682],
        [0.9556, 0.9761, 0.5934]])

In [133]:
torch.relu(m)

tensor([[0.6936, 1.1222, 0.3315],
        [1.8549, 1.2494, 0.9331]])

In [134]:
m.relu_()

tensor([[0.6936, 1.1222, 0.3315],
        [1.8549, 1.2494, 0.9331]])

In [135]:
m

tensor([[0.6936, 1.1222, 0.3315],
        [1.8549, 1.2494, 0.9331]])

## Copying a Tensor

> Add blockquote

In [136]:
a = torch.rand(2,3)
a

tensor([[0.3124, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])

In [138]:
b = a
print(b)

tensor([[0.3124, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])


In [139]:
a[0][0] = 0
print(a)

tensor([[0.0000, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])


In [140]:
print ( b)

tensor([[0.0000, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])


In [141]:
id(a)

136686237969504

In [142]:
id(b)

136686237969504

In [143]:
a


tensor([[0.0000, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])

In [144]:
b

tensor([[0.0000, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])

In [145]:
b = a.clone()

In [146]:
b

tensor([[0.0000, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])

In [147]:
a[0] = 10

In [148]:
a

tensor([[10.0000, 10.0000, 10.0000],
        [ 0.9815,  0.1132,  0.4783]])

In [149]:
b

tensor([[0.0000, 0.9431, 0.8519],
        [0.9815, 0.1132, 0.4783]])

In [150]:
id(a)

136686237969504

In [151]:
id(b)

136686237410928

# Tensor Operations on GPU

In [153]:
torch.cuda.is_available()

True

In [154]:
device = torch.device("cuda")

In [158]:
# creating new tensor on GPU
torch.randint(size=(2,2), low=0, high=20, device=device)

tensor([[17,  7],
        [ 4,  2]], device='cuda:0')

# Reshaping the Tensor

In [159]:
a = torch.ones(4,4)

In [160]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [161]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [164]:
b = torch.rand(2,3,4)
b


tensor([[[0.1292, 0.1719, 0.9127, 0.6818],
         [0.1953, 0.9991, 0.1133, 0.0135],
         [0.1450, 0.7819, 0.3134, 0.2983]],

        [[0.3436, 0.2028, 0.9792, 0.4947],
         [0.3617, 0.9687, 0.0359, 0.3041],
         [0.9867, 0.1290, 0.6887, 0.1637]]])

In [166]:
b.permute(2,1,0)

tensor([[[0.1292, 0.3436],
         [0.1953, 0.3617],
         [0.1450, 0.9867]],

        [[0.1719, 0.2028],
         [0.9991, 0.9687],
         [0.7819, 0.1290]],

        [[0.9127, 0.9792],
         [0.1133, 0.0359],
         [0.3134, 0.6887]],

        [[0.6818, 0.4947],
         [0.0135, 0.3041],
         [0.2983, 0.1637]]])

In [168]:
# unseques
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [169]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [170]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [171]:
# sequeeze
d = torch.rand(1,20)

In [172]:
import torch


In [173]:
x = torch.tensor(3.0, requires_grad=True)

In [174]:
x

tensor(3., requires_grad=True)

In [175]:
y = x**2

In [176]:
y

tensor(9., grad_fn=<PowBackward0>)

In [177]:
y.backward()

In [178]:
x.grad

tensor(6.)

In [199]:
x = torch.tensor(4.0, requires_grad=True)

In [200]:
y = x**2

In [201]:
z = torch.sin(y)

In [202]:
z


tensor(-0.2879, grad_fn=<SinBackward0>)

In [203]:
y

tensor(16., grad_fn=<PowBackward0>)

In [204]:
x

tensor(4., requires_grad=True)

In [206]:
z.backward()

In [207]:
x.grad

tensor(-7.6613)

In [208]:
x = torch.tensor(6.5)
y = torch.tensor(0.0)
w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [210]:
# Cross entropy loss
def binary_cross_entropy_loss(prediction, target):
  eplsion = 1e-8
  prediction = torch.clamp(prediction, eplsion, 1-eplsion)
  return -(target * torch.log(prediction) + (1-target)* torch.log(1-prediction))

In [211]:
z = w*x + b
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy_loss(y_pred, y)

In [212]:
print("Final Loss = ", loss)

Final Loss =  tensor(6.5015)


In [216]:
from prompt_toolkit.shortcuts.dialogs import yes_no_dialog
# Backpropagation
dloss_dy_pred = (y_pred - y) / (y_pred * (1 - y_pred))

dy_pred_dz = y_pred * (1 - y_pred)

dz_dw = x

dz_db = 1

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [217]:
print(f"Manual Gradient of loss w.r.t weight(dw) = ", {dL_dw})
print(f"Manual Gradient of loss w.r.t bias(db) = ", {dL_db})

Manual Gradient of loss w.r.t weight(dw) =  {tensor(6.4902)}
Manual Gradient of loss w.r.t bias(db) =  {tensor(0.9985)}


In [218]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [219]:
w

tensor(1., requires_grad=True)

In [220]:
b

tensor(0., requires_grad=True)

In [221]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [223]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [225]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [226]:
loss.backward()

In [227]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [232]:
x = torch.tensor([1.0, 2.0, 0.90], requires_grad=True)
y = torch.tensor(1.0)
w = torch.tensor(0.001)
b = torch.tensor(0.0)


In [231]:
z = w*y + b
z

tensor(0.0010)

In [234]:
y = (x**2).mean()
y

tensor(1.9367, grad_fn=<MeanBackward0>)

In [235]:
y.backward()

In [237]:
x.grad


tensor([0.6667, 1.3333, 0.6000])