In [40]:
import torch


In [41]:
input = torch.rand([5,10])
# ✅ binary targets must be 0/1 and match output shape (5,1)
# y = torch.tensor([[1.0],[0.0],[1.0],[0.0],[1.0]])   # shape (5,1)
y = torch.ones(5,1)

In [42]:
class MySimpleNN():
   def __init__(self, input):
      
   # define the weights
    self.weights = torch.rand(input.shape[1], 1,dtype=torch.float32, requires_grad=True)

  #. bias
    self.bias = torch.zeros(1, dtype=torch.float32,  requires_grad=True)


   def forward(self, input):
    z = torch.matmul(input, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

   def calculate_loss(self, y, y_pred):
     epsilon = 1e-7
     y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
     loss = -(y * torch.log(y_pred) + ((1 - y) * torch.log(1 - y_pred))).mean()
     return loss


In [43]:
lr = 0.1
epochs = 10

In [44]:
# create the model
model = MySimpleNN(input)
print(model.weights)
print(model.bias)

for epoch in range(epochs):
 # forward pss
  forward = model.forward(input)
  print(forward)

  # backward
  loss = model.calculate_loss(y, forward)
  print(f"epoch {epoch} loss:", loss.item())

  # forward
  loss.backward()
  # updates the weights and bias - 
  with torch.no_grad():
   model.weights -= lr*model.weights.grad
   model.bias -= lr*model.bias.grad

   model.weights.grad.zero_()
   model.bias.grad.zero_()

tensor([[0.4303],
        [0.1003],
        [0.0136],
        [0.1907],
        [0.2870],
        [0.8036],
        [0.8616],
        [0.6483],
        [0.3007],
        [0.8278]], requires_grad=True)
tensor([0.], requires_grad=True)
tensor([[0.8681],
        [0.9116],
        [0.9572],
        [0.9416],
        [0.9197]], grad_fn=<SigmoidBackward0>)
epoch 0 loss: 0.08432845771312714
tensor([[0.8715],
        [0.9139],
        [0.9587],
        [0.9436],
        [0.9217]], grad_fn=<SigmoidBackward0>)
epoch 1 loss: 0.08188091218471527
tensor([[0.8747],
        [0.9160],
        [0.9602],
        [0.9454],
        [0.9236]], grad_fn=<SigmoidBackward0>)
epoch 2 loss: 0.07956887781620026
tensor([[0.8777],
        [0.9181],
        [0.9616],
        [0.9472],
        [0.9254]], grad_fn=<SigmoidBackward0>)
epoch 3 loss: 0.07738165557384491
tensor([[0.8806],
        [0.9201],
        [0.9629],
        [0.9488],
        [0.9271]], grad_fn=<SigmoidBackward0>)
epoch 4 loss: 0.07530953735113144
t

# CODE 2

In [45]:
x = torch.rand([5,5])
y = torch.tensor(1.0)

In [46]:
class MyBasicNN():
    def __init__(self, x):
        self.w = torch.ones(x.shape[1], 4, dtype=torch.float32, requires_grad=True)
        self.b = torch.zeros(1, dtype=torch.float32, requires_grad=True)

    # for forward pss
    def forward(self, x):
        z = torch.matmul(x,self.w) + self.b
        y_pred = (torch.sigmoid(z)).mean()
        return y_pred
    
    def loss_function(self, y, y_pred):
        loss = torch.binary_cross_entropy_with_logits(y, y_pred)
        return y_pred
    
    # ✅ evaluation
    def evaluate(self, x, y, threshold=0.5):
        with torch.no_grad():
            y_prob = self.forward(x)
            y_hat = (y_prob>=threshold).float()
            accuracy = (y_hat == y).float()
            return y_hat, y_prob, accuracy

In [47]:
learning_rate = 0.01
epochs = 10

In [48]:
model = MyBasicNN(x)

for epoch in range(epochs):
  # forward
  y_pred = model.forward(x)
  print(y_pred)
  # loss
  loss = model.loss_function(y, y_pred)
  print(loss)

  # backward
  loss.backward()

# update the weights and baises
  with torch.no_grad():
    model.w -=  learning_rate*model.w.grad
    model.b -= learning_rate*model.b.grad
    print(model.w)
    print(model.b)

    model.w.grad.zero_()
    model.b.grad.zero_()

# after training loop
y_prob, y_hat, acc = model.evaluate(x, y)

print("Evaluation:")
print("probability:", y_prob.item())
print("predicted label:", int(y_hat.item()))
print("true label:", int(y.item()))
print("accuracy:", float(acc.item()))

tensor(0.8982, grad_fn=<MeanBackward0>)
tensor(0.8982, grad_fn=<MeanBackward0>)
tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [0.9999, 0.9999, 0.9999, 0.9999],
        [0.9999, 0.9999, 0.9999, 0.9999],
        [0.9999, 0.9999, 0.9999, 0.9999],
        [0.9999, 0.9999, 0.9999, 0.9999]], requires_grad=True)
tensor([-0.0009], requires_grad=True)
tensor(0.8981, grad_fn=<MeanBackward0>)
tensor(0.8981, grad_fn=<MeanBackward0>)
tensor([[0.9999, 0.9999, 0.9999, 0.9999],
        [0.9999, 0.9999, 0.9999, 0.9999],
        [0.9998, 0.9998, 0.9998, 0.9998],
        [0.9998, 0.9998, 0.9998, 0.9998],
        [0.9998, 0.9998, 0.9998, 0.9998]], requires_grad=True)
tensor([-0.0017], requires_grad=True)
tensor(0.8980, grad_fn=<MeanBackward0>)
tensor(0.8980, grad_fn=<MeanBackward0>)
tensor([[0.9999, 0.9999, 0.9999, 0.9999],
        [0.9998, 0.9998, 0.9998, 0.9998],
        [0.9997, 0.9997, 0.9997, 0.9997],
        [0.9997, 0.9997, 0.9997, 0.9997],
        [0.9997, 0.9997, 0.9997, 0.9997]], requires_gr

# code 3

In [98]:
!pip3 install torchviz  # -- run on terminal

from torchviz import make_dot

input = torch.tensor([0.1, 0.2, 0.3, 0.4]) # 4 inputs
y = torch.tensor(1.0)

class MyNeuralNetworks():
    def __init__(self, input):
        self.w1 = torch.rand(input.shape[0], 3, dtype=torch.float32, requires_grad=True)
        self.b1 = torch.zeros(3, dtype=torch.float32, requires_grad=True)

        # for 2nd layer
        self.w2 = torch.rand(3, 2, dtype=torch.float32, requires_grad=True)
        self.b2 = torch.zeros(2, dtype=torch.float32, requires_grad=True)

        # final layer with 1 neuron
        self.w3 = torch.rand(2, 1, dtype=torch.float32, requires_grad=True)
        self.b3 = torch.zeros(1, dtype=torch.float32, requires_grad=True)

    def forward(self, input):
        z1 = torch.matmul(input, self.w1)+ self.b1
        a1 = torch.relu(z1)

        z2 = torch.matmul(a1, self.w2) + self.b2
        a2 = torch.relu(z2)

        z3 = torch.matmul(a2, self.w3) + self.b3
        y_pred = torch.sigmoid(z3)

        return y_pred
    
    # loss
    def loss_function(self, y, y_pred):
        loss = torch.binary_cross_entropy_with_logits(y, y_pred)
        return loss



Defaulting to user installation because normal site-packages is not writeable


In [99]:
lr = 0.01
epochs = 10

In [101]:
model = MyNeuralNetworks(input)

for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(input)
    # print("forward pass " , y_pred)

    # loss
    loss = model.loss_function(y, y_pred)
    print("loss:", loss)

    # back propagation
    loss.backward()

    # update the learnable parameters
    with torch.no_grad():
     model.w1 -= lr*model.w1.grad
     model.b1 -= lr*model.b1.grad
     model.w2 -= lr*model.w2.grad
     model.b2 -= lr*model.b2.grad
     model.w3 -= lr*model.w3.grad
     model.b3 -= lr*model.b3.grad

     model.w1.grad.zero_
     model.w2.grad.zero_
     model.w3.grad.zero_
     model.b1.grad.zero_ 
     model.b2.grad.zero_
     model.b3.grad.zero_


loss: tensor([0.5120], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.5099], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.5058], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.4997], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.4917], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.4821], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.4709], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.4584], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.4450], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
loss: tensor([0.4310], grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [ ]:
make_dot(loss, params={
        "w1": w1, "b1": b1,
        "w2": w2, "b2": b2,
        "w3": w3, "b3": b3

})

NameError: name 'w1' is not defined